"""Add chat and llm usage tables

Revision ID: c51f679e51dd
Revises:
Create Date: 2026-09-12 11:11:01.417994
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c51f679e51dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "llm_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "input_price",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "cached_input_price",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "cache_write_price",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "output_price",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_price >= 0 AND cached_input_price >= 0 AND cache_write_price >= 0 AND output_price >= 0",
            name="ck_llm_models_prices_not_negative",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_id", "name", name="uq_llm_models_provider_name"
        ),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TEXT", name="message_type"),
            server_default="TEXT",
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_by",
            sa.Enum("USER", "MODEL", "SYSTEM", name="message_author"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_chat_id_created_at",
        "messages",
        ["chat_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "llm_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("llm_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "ERROR", name="llm_call_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "input_tokens", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "cached_input_tokens",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "cache_write_tokens",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "output_tokens", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "reasoning_tokens",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "input_price", sa.Numeric(precision=12, scale=6), nullable=False
        ),
        sa.Column(
            "cached_input_price",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
        ),
        sa.Column(
            "cache_write_price",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
        ),
        sa.Column(
            "output_price", sa.Numeric(precision=12, scale=6), nullable=False
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=14, scale=8),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'ERROR' OR error IS NULL",
            name="ck_llm_messages_error_only_when_failed",
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND cached_input_tokens >= 0 AND cache_write_tokens >= 0 AND output_tokens >= 0 AND reasoning_tokens >= 0 AND cost >= 0",
            name="ck_llm_messages_amounts_not_negative",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["llm_id"],
            ["llm_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_llm_messages_chat_id_created_at",
        "llm_messages",
        ["chat_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_llm_messages_created_at",
        "llm_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_llm_messages_llm_id_created_at",
        "llm_messages",
        ["llm_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "llm_message_contents",
        sa.Column("llm_message_id", sa.Integer(), nullable=False),
        sa.Column("input_content", sa.Text(), nullable=False),
        sa.Column("output_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["llm_message_id"], ["llm_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("llm_message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_message_contents")
    op.drop_index(
        "ix_llm_messages_llm_id_created_at", table_name="llm_messages"
    )
    op.drop_index("ix_llm_messages_created_at", table_name="llm_messages")
    op.drop_index(
        "ix_llm_messages_chat_id_created_at", table_name="llm_messages"
    )
    op.drop_table("llm_messages")
    op.drop_index("ix_messages_chat_id_created_at", table_name="messages")
    op.drop_table("messages")
    op.drop_table("llm_models")
    op.drop_table("llm_providers")
    op.drop_table("chats")
    # ### end Alembic commands ###

    # SQLAlchemy creates these types along with the tables that use them,
    # but Alembic does not generate the matching drops, which would leave
    # the next upgrade failing on a type that already exists
    for enum_name in ("llm_call_status", "message_author", "message_type"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
